name:                open-dofus-game
version:             0.1.0.0
github:              "nerded1337/open-dofus"
license:             GPL-3
author:              "nerded"
maintainer:          "nerded.nerded@gmail.com"
copyright:           "2019 nerded"

extra-source-files:
- README.md

description:
  Please see the README on GitHub at <https://github.com/nerded1337/open-dofus#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- rio
- stm
- stm-containers
- containers
- unordered-containers
- hashtables
- vector
- directory
- lens
- linear
- aeson
- o-clock
- chronos
- mtl
- dlist
- primitive
- uuid
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- attoparsec
- unagi-chan
- compact
- uri-encode
- bitwise-enum
- base64-bytestring
- streamly
- open-dofus-core
- open-dofus-db

default-extensions:
  - NoImplicitPrelude 
  - Strict

executables:
  open-dofus-game:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
      - -fno-full-laziness
      - -ffun-to-thunk
      - -funbox-strict-fields
      - -feager-blackholing
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -fstatic-argument-transformation
      - -fspec-constr-keen
      - -flate-specialise
      - -flate-dmd-anal
      - -O2
      - -rtsopts
      - "\"-with-rtsopts=-N -H1024m -A128m -AL128m -Iw300 -qn8 -xn -S\""
