name:                open-dofus-auth
version:             0.1.0.0
github:              "nerded1337/open-dofus"
license:             GPL-3
author:              "nerded"
maintainer:          "nerded.nerded@gmail.com"
copyright:           "2019 nerded"

extra-source-files:
- README.md

description:
  Please see the README on GitHub at <https://github.com/nerded1337/open-dofus#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- network
- streamly
- stm
- stm-containers
- MonadRandom
- containers
- vector
- directory
- lens
- aeson
- mtl
- uuid
- rio
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- open-dofus-core
- open-dofus-db
- Z-IO

default-extensions:
  - NoImplicitPrelude 

executables:
  open-dofus-auth:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
      - -fno-full-laziness
      - -ffun-to-thunk
      - -funbox-strict-fields
      - -feager-blackholing
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -fstatic-argument-transformation
      - -fspec-constr-keen
      - -flate-specialise
      - -flate-dmd-anal
      - -O2
      - -rtsopts
      - "\"-with-rtsopts=-N -H64m -A64m -AL64m -Iw60 -qn8 -S\""
