name:                open-dofus-core
version:             0.1.0.0
github:              "nerded1337/open-dofus"
license:             GPL-3
author:              "nerded"
maintainer:          "nerded.nerded@gmail.com"
copyright:           "2019 nerded"

extra-source-files:
- README.md

description:
  Please see the README on GitHub at <https://github.com/nerded1337/open-dofus#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- vector
- exceptions
- lens
- scientific
- time
- clock
- containers
- unordered-containers
- vector-binary-instances
- stm
- stm-containers
- directory
- filepath
- path
- dlist
- aeson
- aeson-extra
- aeson-pretty
- mtl
- uuid
- asil
- binary
- attoparsec
- rio
- network
- streamly
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- Z-Data
- Z-IO

default-extensions:
  - NoImplicitPrelude 

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fno-full-laziness
    - -ffun-to-thunk
    - -funbox-strict-fields
    - -feager-blackholing
    - -fspecialise-aggressively
    - -fstatic-argument-transformation
    - -O2
