name:                open-dofus-db
version:             0.1.0.0
github:              "nerded1337/open-dofus"
license:             GPL-3
author:              "nerded"
maintainer:          "nerded.nerded@gmail.com"
copyright:           "2019 nerded"

extra-source-files:
- README.md

description:
  Please see the README on GitHub at <https://github.com/nerded1337/open-dofus#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- scientific
- time
- stm
- containers
- unordered-containers
- vector
- vector-binary-instances
- directory
- filepath
- path
- linear
- aeson
- aeson-extra
- aeson-pretty
- clock
- mtl
- uuid
- text
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple
- asil
- binary
- attoparsec
- lens
- rio
- resource-pool
- natural-transformation
- open-dofus-core

default-extensions:
  - NoImplicitPrelude 
  - Strict

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fno-full-laziness
    - -ffun-to-thunk
    - -funbox-strict-fields
    - -feager-blackholing
    - -fspecialise-aggressively
    - -fstatic-argument-transformation
    - -fspec-constr-keen
    - -flate-specialise
    - -flate-dmd-anal
    - -O2
