on: [push]

name: build

jobs:
  build-stack:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Stack / ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ matrix.os }}-1
      - name: Build
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          stack build --fast
      - name: Test
        run: stack test --fast
